# Generated by Django 4.1.3 on 2023-03-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='date_creation',
        ),
    ]
