# Generated by Django 4.1.3 on 2023-03-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_hotel_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='tel',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
