# Generated by Django 4.1.3 on 2023-03-11 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotel_email_hotel_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='tel',
        ),
    ]
