# Generated by Django 4.1.3 on 2023-03-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_hotel_email_remove_hotel_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='chambreequipement',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='chambreimage',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelequipement',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='HotelImage',
        ),
    ]
