# Generated by Django 4.1.3 on 2023-03-14 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_customer_hotel_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
            preserve_default=False,
        ),
    ]
